cd /data1/fesd1/jthom143/piControl_paper/Figures/SAM
close all

mean_trend_sam = [can_esm2_mean_sam,...
                      ccsm4_mean_sam,...
                      cnrm_cm52_mean_sam,...
                      gfdl_esm2m_mean_sam,...
                      ipsl_cm5a_lr_mean_sam,...
                      ipsl_cm5a_mr_mean_sam,...
                      ipsl_cm5b_lr_mean_sam,...
                      miroc_esm_mean_sam,...
                      miroc_esm_chem_mean_sam,...
                      miroc5_mean_sam,...
                      mpi_esm_lr_mean_sam,...
                      mpi_esm_mr_mean_sam,...
                      mri_cgcm3_mean_sam,...
                      nor_esm1m_m_mean_sam,...
                      nor_esm1m_me_mean_sam];

std_trend_sam = [can_esm2_std_sam,...
                      ccsm4_std_sam,...
                      cnrm_cm52_std_sam,...
                      gfdl_esm2m_std_sam,...
                      ipsl_cm5a_lr_std_sam,...
                      ipsl_cm5a_mr_std_sam,...
                      ipsl_cm5b_lr_std_sam,...
                      miroc_esm_std_sam,...
                      miroc_esm_chem_std_sam,...
                      miroc5_std_sam,...
                      mpi_esm_lr_std_sam,...
                      mpi_esm_mr_std_sam,...
                      mri_cgcm3_std_sam,...
                      nor_esm1m_m_std_sam,...
                      nor_esm1m_me_std_sam];
                  
historical_trend_sam = [can_esm2_sam_trend_30,...
                    ccsm4_sam_trend_30,...
                    cnrm_cm5_sam_trend_30,...
                    gfdl_esm2m_sam_trend_30,...
                    ipsl_cm5a_lr_sam_trend_30,...
                    ipsl_cm5a_mr_sam_trend_30,...
                    ipsl_cm5b_lr_sam_trend_30,...
                    miroc_esm_sam_trend_30,...
                    miroc_esm_chem_sam_trend_30,...
                    miroc5_sam_trend_30,...
                    mpi_esm_lr_sam_trend_30,...
                    mpi_esm_mr_sam_trend_30,...
                    mri_cgcm3_sam_trend_30,...
                    nor_esm1m_m_sam_trend_30,...
                    nor_esm1m_me_sam_trend_30];
                 
                
                
x_axis = 1:length(mean_trend_sam);
x_label = {'  ';'CanESM2'; 'CCSM4'; 'CNRM CM52'; 'GFDL ESM2M'; 'IPSL CM5A LR'; 'IPSL CM5A MR'; 'IPSL CM5B LR'; 'MIROC ESM'; 'MIROC ESM CHEM'; 'MIROC5'; 'MPI ESM LR'; 'MPI ESM MR'; 'MRI CGCM3'; 'NOR ESM1M M'; 'NOR ESM1M ME'; '  '}';

figure(1)
h1 = errorbar(x_axis,mean_trend_sam,2.*std_trend_sam);
hold on 
h2 = plot(x_axis, historical_trend_sam, 'r*');
h3 = hline(sam_trend_30);
h4 = hline(r2_sam_trend_30);
h5 = hline(era_int_sam_trend_30);
set(h3, 'linestyle', '- -', 'linewidth', 2, 'color', [0, 0.8, 0])
set(h4, 'linestyle', '- -', 'linewidth', 2, 'color', [0.9 0.6 0.2])
set(h5, 'linestyle', '- -', 'linewidth', 2, 'color', [0.6 0.03 0.9])
set(h1,'marker','o', 'MarkerFaceColor', 'b')
set(h1,'linestyle','none')
set(gca, 'XTickLabel', x_label)
set(gca, 'XTick', 0:16)
rotateXLabels( gca, 45 )
%ylim([-2.2 2.2])

%print -depsc allmodels_sam_whiskers


                
%% Ensemble Figures
can_esm2_ensemble_trends     = [can_esm2_sam_trend_30, can_esm2_sam_trend_30_e2, can_esm2_sam_trend_30_e3, can_esm2_sam_trend_30_e4, can_esm2_sam_trend_30_e5];
cnrm_cm5_ensemble_trends     = [cnrm_cm5_sam_trend_30, cnrm_cm5_sam_trend_30_e2, cnrm_cm5_sam_trend_30_e3, cnrm_cm5_sam_trend_30_e4, cnrm_cm5_sam_trend_30_e5, cnrm_cm5_sam_trend_30_e6, cnrm_cm5_sam_trend_30_e7, cnrm_cm5_sam_trend_30_e8, cnrm_cm5_sam_trend_30_e9];
ipsl_cm5a_lr_ensemble_trends = [ipsl_cm5a_lr_sam_trend_30, ipsl_cm5a_lr_sam_trend_30_e2, ipsl_cm5a_lr_sam_trend_30_e3, ipsl_cm5a_lr_sam_trend_30_e4, ipsl_cm5a_lr_sam_trend_30_e5, ipsl_cm5a_lr_sam_trend_30_e6];
ipsl_cm5a_mr_ensemble_trends = [ipsl_cm5a_mr_sam_trend_30, ipsl_cm5a_mr_sam_trend_30_e2, ipsl_cm5a_mr_sam_trend_30_e3];
miroc_esm_ensemble_trends    = [miroc_esm_sam_trend_30, miroc_esm_sam_trend_30_e2, miroc_esm_sam_trend_30_e3];
miroc5_ensemble_trends       = [miroc5_sam_trend_30, miroc5_sam_trend_30_e2, miroc5_sam_trend_30_e3, miroc5_sam_trend_30_e4, miroc5_sam_trend_30_e5];
mpi_esm_lr_ensemble_trends   = [mpi_esm_lr_sam_trend_30, mpi_esm_lr_sam_trend_30_e2, mpi_esm_lr_sam_trend_30_e3];
mpi_esm_mr_ensemble_trends   = [mpi_esm_mr_sam_trend_30, mpi_esm_mr_sam_trend_30_e2, mpi_esm_mr_sam_trend_30_e3];
mri_cgcm3_ensemble_trends    = [mri_cgcm3_sam_trend_30, mri_cgcm3_sam_trend_30_e2, mri_cgcm3_sam_trend_30_e3];
nor_esm1m_m_ensemble_trends  = [nor_esm1m_m_sam_trend_30, nor_esm1m_m_sam_trend_30_e2, nor_esm1m_m_sam_trend_30_e3];


mean_ensemble_trends = [nanmean(can_esm2_ensemble_trends),...
                        ccsm4_sam_trend_30,...
                        nanmean(cnrm_cm5_ensemble_trends),...
                        gfdl_esm2m_sam_trend_30,...
                        nanmean(ipsl_cm5a_lr_ensemble_trends),...
                        nanmean(ipsl_cm5a_mr_ensemble_trends),...
                        ipsl_cm5b_lr_sam_trend_30,...
                        nanmean(miroc_esm_ensemble_trends),...
                        miroc_esm_chem_sam_trend_30,...
                        nanmean(miroc5_ensemble_trends),...
                        nanmean(mpi_esm_lr_ensemble_trends),...
                        nanmean(mpi_esm_mr_ensemble_trends),...
                        nanmean(mri_cgcm3_ensemble_trends),...
                        nanmean(nor_esm1m_m_ensemble_trends),...
                        nor_esm1m_me_sam_trend_30];
                    
E_ensemble_trends =    [max(can_esm2_ensemble_trends)-nanmean(can_esm2_ensemble_trends),...
                        NaN,...
                        max(cnrm_cm5_ensemble_trends)-nanmean(cnrm_cm5_ensemble_trends),...
                        NaN,...
                        max(ipsl_cm5a_lr_ensemble_trends)-nanmean(ipsl_cm5a_lr_ensemble_trends),...
                        max(ipsl_cm5a_mr_ensemble_trends)-nanmean(ipsl_cm5a_mr_ensemble_trends),...
                        NaN,...
                        max(miroc_esm_ensemble_trends)-nanmean(miroc_esm_ensemble_trends),...
                        NaN,...
                        max(miroc5_ensemble_trends)-nanmean(miroc5_ensemble_trends),...
                        max(mpi_esm_lr_ensemble_trends)-nanmean(mpi_esm_lr_ensemble_trends),...
                        max(mpi_esm_mr_ensemble_trends)-nanmean(mpi_esm_mr_ensemble_trends),...
                        max(mri_cgcm3_ensemble_trends)-nanmean(mri_cgcm3_ensemble_trends),...
                        max(nor_esm1m_m_ensemble_trends)-nanmean(nor_esm1m_m_ensemble_trends),...
                        NaN];
                        
                
                    
x_axis = 1:length(mean_trend_sam);
x_label = {'  ';'CanESM2'; 'CCSM4'; 'CNRM CM5'; 'GFDL ESM2M'; 'IPSL CM5A LR'; 'IPSL CM5A MR'; 'IPSL CM5B LR'; 'MIROC ESM'; 'MIROC ESM CHEM'; 'MIROC5'; 'MPI ESM LR'; 'MPI ESM MR'; 'MRI CGCM3'; 'NOR ESM1M M'; 'NOR ESM1M ME'; '  '}';

figure(3)
h1 = errorbar(x_axis,mean_trend_sam,2.*std_trend_sam);
hold on 
h2 = plot(x_axis, historical_trend_sam, 'r*');
h3 = hline(sam_trend_30);
h8 = hline(r2_sam_trend_30);
h9 = hline(era_int_sam_trend_30);
set(h3, 'linestyle', '- -', 'linewidth', 2, 'color', [0, 0.8, 0])
set(h8, 'linestyle', '- -', 'linewidth', 2, 'color', [0.9 0.6 0.2])
set(h9, 'linestyle', '- -', 'linewidth', 2, 'color', [0.6 0.03 0.9])
h4 = plot(1, can_esm2_ensemble_trends, 'r*');
h5 = plot(3, cnrm_cm5_ensemble_trends, 'r*');
h6 = plot(5, ipsl_cm5a_lr_ensemble_trends, 'r*');
h7 = plot(6, ipsl_cm5a_mr_ensemble_trends, 'r*');
h7 = plot(8, miroc_esm_ensemble_trends, 'r*');
h7 = plot(10, miroc5_ensemble_trends, 'r*');
h7 = plot(11, mpi_esm_lr_ensemble_trends, 'r*');
h7 = plot(12, mpi_esm_mr_ensemble_trends, 'r*');
h7 = plot(13, mri_cgcm3_ensemble_trends, 'r*');
h7 = plot(14, nor_esm1m_m_ensemble_trends, 'r*');

set(h1,'marker','o', 'MarkerFaceColor', 'b')
set(h1,'linestyle','none')
set(gca, 'XTickLabel', x_label)
set(gca, 'XTick', 0:16)
rotateXLabels( gca, 45 )
title('SAM 25 year linear trends')
ylabel('Zonal Pressure Difference (mb/25years)')

print -depsc allmodels_sam_whiskers_ensemble

cd /data1/fesd1/jthom143/piControl_paper
