figure(1)
plot(percentile_jet(1), percentile_sam(1), '*', 'markersize', 12, 'linewidth', 2)
hold on 
plot(percentile_jet(2), percentile_sam(2), 'r*', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(3), percentile_sam(3), 'g*', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(4), percentile_sam(4), 'c*', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(5), percentile_sam(5), 'k*', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(6), percentile_sam(6), 'o', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(7), percentile_sam(7), 'or', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(8), percentile_sam(8), 'og', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(9), percentile_sam(9), 'oc', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(10), percentile_sam(10), 'ok', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(11), percentile_sam(11), 'x', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(12), percentile_sam(12), 'xr', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(13), percentile_sam(13), 'xg', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(14), percentile_sam(14), 'xc', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(15), percentile_sam(15), 'xk', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(16), percentile_sam(16), '+', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(17), percentile_sam(17), '+r', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(18), percentile_sam(18), '+g', 'markersize', 12, 'linewidth', 2)
%plot(percentile_jet(19), percentile_sam(19), '+c', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(20), percentile_sam(20), '+k', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(21), percentile_sam(21), 'd', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(22), percentile_sam(22), 'dr', 'markersize', 12, 'linewidth', 2)
legend('CanESM2', 'CCSM4','CMCC CESM', 'CMCC CM', 'CMCC CMs', 'CNRM CM5', 'CNRM CM5-2','GFDL ESM2G','GFDL ESM2M', 'IPSL CM5a LR', 'IPSL CM5a MR',...
    'IPSL CM5b LR', 'MIROC ESM', 'MIROC ESM CHEM','MIROC5','MPI ESM LR', 'MPI ESM MR','MRI CGCM3', 'NOR ESM1m ME',...
    'CM2Mc', 'CM2.1');
set(gca, 'fontsize', 12)
set(gcf, 'position', [100, 100, 1049, 895])
% xlim([0 12e-3])
% ylim([0 4])
xlabel('95th Percentile Jet Magnitude Trends', 'fontsize', 12)
ylabel('95th Pecentile SAM Trends', 'fontsize', 12)

figure(2)
plot(percentile_loc(1), percentile_sam(1), '*', 'markersize', 12, 'linewidth', 2)
hold on 
plot(percentile_loc(2), percentile_sam(2), 'r*', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(3), percentile_sam(3), 'g*', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(4), percentile_sam(4), 'c*', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(5), percentile_sam(5), 'k*', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(6), percentile_sam(6), 'o', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(7), percentile_sam(7), 'or', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(8), percentile_sam(8), 'og', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(9), percentile_sam(9), 'oc', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(10), percentile_sam(10), 'ok', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(11), percentile_sam(11), 'x', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(12), percentile_sam(12), 'xr', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(13), percentile_sam(13), 'xg', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(14), percentile_sam(14), 'xc', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(15), percentile_sam(15), 'xk', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(16), percentile_sam(16), '+', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(17), percentile_sam(17), '+r', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(18), percentile_sam(18), '+g', 'markersize', 12, 'linewidth', 2)
%plot(percentile_loc(19), percentile_sam(19), '+c', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(20), percentile_sam(20), '+k', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(21), percentile_sam(21), 'd', 'markersize', 12, 'linewidth', 2)
plot(percentile_loc(22), percentile_sam(22), 'dr', 'markersize', 12, 'linewidth', 2)
legend('CanESM2', 'CCSM4','CMCC CESM', 'CMCC CM', 'CMCC CMs', 'CNRM CM5', 'CNRM CM5-2','GFDL ESM2G','GFDL ESM2M', 'IPSL CM5a LR', 'IPSL CM5a MR',...
    'IPSL CM5b LR', 'MIROC ESM', 'MIROC ESM CHEM','MIROC5','MPI ESM LR', 'MPI ESM MR','MRI CGCM3', 'NOR ESM1m ME',...
    'CM2Mc', 'CM2.1');set(gca, 'fontsize', 12)
set(gcf, 'position', [100, 100, 1049, 895])
% xlim([0 4])
% ylim([0 4])
xlabel('95th Percentile Jet Location Trends', 'fontsize', 12)
ylabel('95th Pecentile SAM Trends', 'fontsize', 12)

figure(3)
plot(percentile_jet(1), percentile_loc(1), '*', 'markersize', 12, 'linewidth', 2)
hold on
plot(percentile_jet(2), percentile_loc(2), 'r*', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(3), percentile_loc(3), 'g*', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(4), percentile_loc(4), 'c*', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(5), percentile_loc(5), 'k*', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(6), percentile_loc(6), 'o', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(7), percentile_loc(7), 'or', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(8), percentile_loc(8), 'og', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(9), percentile_loc(9), 'oc', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(10), percentile_loc(10), 'ok', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(11), percentile_loc(11), 'x', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(12), percentile_loc(12), 'xr', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(13), percentile_loc(13), 'xg', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(14), percentile_loc(14), 'xc', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(15), percentile_loc(15), 'xk', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(16), percentile_loc(16), '+', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(17), percentile_loc(17), '+r', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(18), percentile_loc(18), '+g', 'markersize', 12, 'linewidth', 2)
%plot(percentile_jet(19), percentile_loc(19), '+c', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(20), percentile_loc(20), '+k', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(21), percentile_loc(21), 'd', 'markersize', 12, 'linewidth', 2)
plot(percentile_jet(22), percentile_loc(22), 'dr', 'markersize', 12, 'linewidth', 2)
legend('CanESM2', 'CCSM4','CMCC CESM', 'CMCC CM', 'CMCC CMs', 'CNRM CM5', 'CNRM CM5-2','GFDL ESM2G','GFDL ESM2M', 'IPSL CM5a LR', 'IPSL CM5a MR',...
    'IPSL CM5b LR', 'MIROC ESM', 'MIROC ESM CHEM','MIROC5','MPI ESM LR', 'MPI ESM MR','MRI CGCM3', 'NOR ESM1m ME',...
    'CM2Mc', 'CM2.1');
set(gca, 'fontsize', 12)
set(gcf, 'position', [100, 100, 1049, 895])
%xlim([0 12e-3])
%ylim([0 4])
xlabel('95th Percentile Jet Magnitude Trends', 'fontsize', 12)
ylabel('95th Pecentile Jet Location Trends', 'fontsize', 12)

figure(4)
plot(nanmean(can_esm2_jet_ann), percentile_jet(1), '*', 'markersize', 12, 'linewidth', 2)
hold on 
plot(nanmean(ccsm4_jet_ann), percentile_jet(2), 'r*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cmcc_cesm_jet_ann), percentile_jet(3), 'g*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cmcc_cm_jet_ann), percentile_jet(4), 'c*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cmcc_cms_jet_ann), percentile_jet(5), 'k*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cnrm_cm5_jet_ann), percentile_jet(6), 'o', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cnrm_cm52_jet_ann),  percentile_jet(7),'or', 'markersize', 12, 'linewidth', 2)
plot(nanmean(gfdl_esm2g_jet_ann), percentile_jet(8), 'og', 'markersize', 12, 'linewidth', 2)
plot(nanmean(gfdl_esm2m_jet_ann), percentile_jet(9), 'oc', 'markersize', 12, 'linewidth', 2)
plot(nanmean(ipsl_cm5a_lr_jet_ann), percentile_jet(10), 'ok', 'markersize', 12, 'linewidth', 2)
plot(nanmean(ipsl_cm5a_mr_jet_ann), percentile_jet(11), 'x', 'markersize', 12, 'linewidth', 2)
plot(nanmean(ipsl_cm5b_lr_jet_ann), percentile_jet(12), 'xr', 'markersize', 12, 'linewidth', 2)
plot(nanmean(miroc_esm_jet_ann), percentile_jet(13), 'xg', 'markersize', 12, 'linewidth', 2)
plot(nanmean(miroc_esm_chem_jet_ann), percentile_jet(14), 'xc', 'markersize', 12, 'linewidth', 2)
plot(nanmean(miroc5_jet_ann), percentile_jet(15), 'xk', 'markersize', 12, 'linewidth', 2)
plot(nanmean(mpi_esm_lr_jet_ann), percentile_jet(16), '+', 'markersize', 12, 'linewidth', 2)
plot(nanmean(mpi_esm_mr_jet_ann), percentile_jet(17), '+r', 'markersize', 12, 'linewidth', 2)
plot(nanmean(mri_cgcm3_jet_ann), percentile_jet(18), '+g', 'markersize', 12, 'linewidth', 2)
%plot(percentile_sam(19), '+c', 'markersize', 12, 'linewidth', 2)
plot(nanmean(nor_esm1m_me_jet_ann), percentile_jet(20), '+k', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cm2mc_jet_ann), percentile_jet(21),'d', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cm21_jet_ann), percentile_jet(22), 'dr', 'markersize', 12, 'linewidth', 2)
legend('CanESM2', 'CCSM4','CMCC CESM', 'CMCC CM', 'CMCC CMs', 'CNRM CM5', 'CNRM CM5-2','GFDL ESM2G','GFDL ESM2M', 'IPSL CM5a LR', 'IPSL CM5a MR',...
    'IPSL CM5b LR', 'MIROC ESM', 'MIROC ESM CHEM','MIROC5','MPI ESM LR', 'MPI ESM MR','MRI CGCM3', 'NOR ESM1m ME',...
    'CM2Mc', 'CM2.1');
set(gca, 'fontsize', 12)
set(gcf, 'position', [100, 100, 1049, 895])
% xlim([0 12e-3])
% ylim([0 4])
ylabel('95th Percentile Jet Magnitude Trends', 'fontsize', 12)
xlabel('Average Jet Strength', 'fontsize', 12)


figure(5)
plot(nanmean(can_esm2_jet_loc_ann),percentile_loc(1), '*', 'markersize', 12, 'linewidth', 2)
hold on 
plot(nanmean(ccsm4_jet_loc_ann),percentile_loc(2), 'r*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cmcc_cesm_jet_loc_ann), percentile_loc(3),'g*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cmcc_cm_jet_loc_ann), percentile_loc(4),'c*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cmcc_cms_jet_loc_ann), percentile_loc(5),'k*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cnrm_cm5_jet_loc_ann), percentile_loc(6),'o', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cnrm_cm52_jet_loc_ann), percentile_loc(7),'or', 'markersize', 12, 'linewidth', 2)
plot(nanmean(gfdl_esm2g_jet_loc_ann), percentile_loc(8),'og', 'markersize', 12, 'linewidth', 2)
plot(nanmean(gfdl_esm2m_jet_loc_ann), percentile_loc(9),'oc', 'markersize', 12, 'linewidth', 2)
plot(nanmean(ipsl_cm5a_lr_jet_loc_ann), percentile_loc(10),'ok', 'markersize', 12, 'linewidth', 2)
plot(nanmean(ipsl_cm5a_mr_jet_loc_ann), percentile_loc(11),'x', 'markersize', 12, 'linewidth', 2)
plot(nanmean(ipsl_cm5b_lr_jet_loc_ann), percentile_loc(12),'xr', 'markersize', 12, 'linewidth', 2)
plot(nanmean(miroc_esm_jet_loc_ann), percentile_loc(13),'xg', 'markersize', 12, 'linewidth', 2)
plot(nanmean(miroc_esm_chem_jet_loc_ann), percentile_loc(14),'xc', 'markersize', 12, 'linewidth', 2)
plot(nanmean(miroc5_jet_loc_ann), percentile_loc(15),'xk', 'markersize', 12, 'linewidth', 2)
plot(nanmean(mpi_esm_lr_jet_loc_ann), percentile_loc(16),'+', 'markersize', 12, 'linewidth', 2)
plot(nanmean(mpi_esm_mr_jet_loc_ann), percentile_loc(17),'+r', 'markersize', 12, 'linewidth', 2)
plot(nanmean(mri_cgcm3_jet_loc_ann), percentile_loc(18),'+g', 'markersize', 12, 'linewidth', 2)
%plot(percentile_loc(19), percentile_sam(19), '+c', 'markersize', 12, 'linewidth', 2)
plot(nanmean(nor_esm1m_me_jet_loc_ann),percentile_loc(20), '+k', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cm2mc_jet_loc_ann),percentile_loc(21), 'd', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cm21_jet_loc_ann),percentile_loc(22), 'dr', 'markersize', 12, 'linewidth', 2)
legend('CanESM2', 'CCSM4','CMCC CESM', 'CMCC CM', 'CMCC CMs', 'CNRM CM5', 'CNRM CM5-2','GFDL ESM2G','GFDL ESM2M', 'IPSL CM5a LR', 'IPSL CM5a MR',...
    'IPSL CM5b LR', 'MIROC ESM', 'MIROC ESM CHEM','MIROC5','MPI ESM LR', 'MPI ESM MR','MRI CGCM3', 'NOR ESM1m ME',...
    'CM2Mc', 'CM2.1');
set(gca, 'fontsize', 12)
set(gcf, 'position', [100, 100, 1049, 895])
% xlim([0 12e-3])
% ylim([0 4])
ylabel('95th Percentile Jet Location Trends', 'fontsize', 12)
xlabel('Average Jet Location', 'fontsize', 12)

figure(6)
plot(nanmean(can_esm2_jet_DJF), percentile_jet(1), '*', 'markersize', 12, 'linewidth', 2)
hold on 
plot(nanmean(ccsm4_jet_DJF), percentile_jet(2), 'r*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cmcc_cesm_jet_DJF), percentile_jet(3), 'g*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cmcc_cm_jet_DJF), percentile_jet(4), 'c*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cmcc_cms_jet_DJF), percentile_jet(5), 'k*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cnrm_cm5_jet_DJF), percentile_jet(6), 'o', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cnrm_cm52_jet_DJF),  percentile_jet(7),'or', 'markersize', 12, 'linewidth', 2)
plot(nanmean(gfdl_esm2g_jet_DJF), percentile_jet(8), 'og', 'markersize', 12, 'linewidth', 2)
plot(nanmean(gfdl_esm2m_jet_DJF), percentile_jet(9), 'oc', 'markersize', 12, 'linewidth', 2)
plot(nanmean(ipsl_cm5a_lr_jet_DJF), percentile_jet(10), 'ok', 'markersize', 12, 'linewidth', 2)
plot(nanmean(ipsl_cm5a_mr_jet_DJF), percentile_jet(11), 'x', 'markersize', 12, 'linewidth', 2)
plot(nanmean(ipsl_cm5b_lr_jet_DJF), percentile_jet(12), 'xr', 'markersize', 12, 'linewidth', 2)
plot(nanmean(miroc_esm_jet_DJF), percentile_jet(13), 'xg', 'markersize', 12, 'linewidth', 2)
plot(nanmean(miroc_esm_chem_jet_DJF), percentile_jet(14), 'xc', 'markersize', 12, 'linewidth', 2)
plot(nanmean(miroc5_jet_DJF), percentile_jet(15), 'xk', 'markersize', 12, 'linewidth', 2)
plot(nanmean(mpi_esm_lr_jet_DJF), percentile_jet(16), '+', 'markersize', 12, 'linewidth', 2)
plot(nanmean(mpi_esm_mr_jet_DJF), percentile_jet(17), '+r', 'markersize', 12, 'linewidth', 2)
plot(nanmean(mri_cgcm3_jet_DJF), percentile_jet(18), '+g', 'markersize', 12, 'linewidth', 2)
%plot(percentile_sam(19), '+c', 'markersize', 12, 'linewidth', 2)
plot(nanmean(nor_esm1m_me_jet_DJF), percentile_jet(20), '+k', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cm2mc_jet_DJF), percentile_jet(21),'d', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cm21_jet_DJF), percentile_jet(22), 'dr', 'markersize', 12, 'linewidth', 2)
legend('CanESM2', 'CCSM4','CMCC CESM', 'CMCC CM', 'CMCC CMs', 'CNRM CM5', 'CNRM CM5-2','GFDL ESM2G','GFDL ESM2M', 'IPSL CM5a LR', 'IPSL CM5a MR',...
    'IPSL CM5b LR', 'MIROC ESM', 'MIROC ESM CHEM','MIROC5','MPI ESM LR', 'MPI ESM MR','MRI CGCM3', 'NOR ESM1m ME',...
    'CM2Mc', 'CM2.1');
set(gca, 'fontsize', 12)
set(gcf, 'position', [100, 100, 1049, 895])
% xlim([0 12e-3])
% ylim([0 4])
ylabel('95th Percentile Jet Magnitude Trends', 'fontsize', 12)
xlabel('Average Jet Strength', 'fontsize', 12)


figure(7)
plot(nanmean(can_esm2_jet_loc_DJF),percentile_loc(1), '*', 'markersize', 12, 'linewidth', 2)
hold on 
plot(nanmean(ccsm4_jet_loc_DJF),percentile_loc(2), 'r*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cmcc_cesm_jet_loc_DJF), percentile_loc(3),'g*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cmcc_cm_jet_loc_DJF), percentile_loc(4),'c*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cmcc_cms_jet_loc_DJF), percentile_loc(5),'k*', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cnrm_cm5_jet_loc_DJF), percentile_loc(6),'o', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cnrm_cm52_jet_loc_DJF), percentile_loc(7),'or', 'markersize', 12, 'linewidth', 2)
plot(nanmean(gfdl_esm2g_jet_loc_DJF), percentile_loc(8),'og', 'markersize', 12, 'linewidth', 2)
plot(nanmean(gfdl_esm2m_jet_loc_DJF), percentile_loc(9),'oc', 'markersize', 12, 'linewidth', 2)
plot(nanmean(ipsl_cm5a_lr_jet_loc_DJF), percentile_loc(10),'ok', 'markersize', 12, 'linewidth', 2)
plot(nanmean(ipsl_cm5a_mr_jet_loc_DJF), percentile_loc(11),'x', 'markersize', 12, 'linewidth', 2)
plot(nanmean(ipsl_cm5b_lr_jet_loc_DJF), percentile_loc(12),'xr', 'markersize', 12, 'linewidth', 2)
plot(nanmean(miroc_esm_jet_loc_DJF), percentile_loc(13),'xg', 'markersize', 12, 'linewidth', 2)
plot(nanmean(miroc_esm_chem_jet_loc_DJF), percentile_loc(14),'xc', 'markersize', 12, 'linewidth', 2)
plot(nanmean(miroc5_jet_loc_DJF), percentile_loc(15),'xk', 'markersize', 12, 'linewidth', 2)
plot(nanmean(mpi_esm_lr_jet_loc_DJF), percentile_loc(16),'+', 'markersize', 12, 'linewidth', 2)
plot(nanmean(mpi_esm_mr_jet_loc_DJF), percentile_loc(17),'+r', 'markersize', 12, 'linewidth', 2)
plot(nanmean(mri_cgcm3_jet_loc_DJF), percentile_loc(18),'+g', 'markersize', 12, 'linewidth', 2)
%plot(percentile_loc(19), percentile_sam(19), '+c', 'markersize', 12, 'linewidth', 2)
plot(nanmean(nor_esm1m_me_jet_loc_DJF),percentile_loc(20), '+k', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cm2mc_jet_loc_DJF),percentile_loc(21), 'd', 'markersize', 12, 'linewidth', 2)
plot(nanmean(cm21_jet_loc_DJF),percentile_loc(22), 'dr', 'markersize', 12, 'linewidth', 2)
legend('CanESM2', 'CCSM4','CMCC CESM', 'CMCC CM', 'CMCC CMs', 'CNRM CM5', 'CNRM CM5-2','GFDL ESM2G','GFDL ESM2M', 'IPSL CM5a LR', 'IPSL CM5a MR',...
    'IPSL CM5b LR', 'MIROC ESM', 'MIROC ESM CHEM','MIROC5','MPI ESM LR', 'MPI ESM MR','MRI CGCM3', 'NOR ESM1m ME',...
    'CM2Mc', 'CM2.1');
set(gca, 'fontsize', 12)
set(gcf, 'position', [100, 100, 1049, 895])
% xlim([0 12e-3])
% ylim([0 4])
ylabel('95th Percentile Jet Location Trends', 'fontsize', 12)
xlabel('Average Jet Location', 'fontsize', 12)