cd /data1/fesd1/jthom143/piControl_paper/Figures/Wind_Jet_Whiskers

mean_trend_jet_mag = [can_esm2_mean_jet,...
                      ccsm4_mean_jet,...
                      cnrm_cm52_mean_jet,...
                      gfdl_esm2m_mean_jet,...
                      ipsl_cm5a_lr_mean_jet,...
                      ipsl_cm5a_mr_mean_jet,...
                      ipsl_cm5b_lr_mean_jet,...
                      miroc_esm_mean_jet,...
                      miroc_esm_chem_mean_jet,...
                      miroc5_mean_jet,...
                      mpi_esm_lr_mean_jet,...
                      mpi_esm_mr_mean_jet,...
                      mri_cgcm3_mean_jet,...
                      nor_esm1m_m_mean_jet,...
                      nor_esm1m_me_mean_jet];

std_trend_jet_mag = [can_esm2_std_jet,...
                      ccsm4_std_jet,...
                      cnrm_cm52_std_jet,...
                      gfdl_esm2m_std_jet,...
                      ipsl_cm5a_lr_std_jet,...
                      ipsl_cm5a_mr_std_jet,...
                      ipsl_cm5b_lr_std_jet,...
                      miroc_esm_std_jet,...
                      miroc_esm_chem_std_jet,...
                      miroc5_std_jet,...
                      mpi_esm_lr_std_jet,...
                      mpi_esm_mr_std_jet,...
                      mri_cgcm3_std_jet,...
                      nor_esm1m_m_std_jet,...
                      nor_esm1m_me_std_jet];
                  
historical_trend = [can_esm2_jet_trend_30_u850,...
                    ccsm4_jet_trend_30_u850,...
                    cnrm_cm5_jet_trend_30_u850,...
                    gfdl_esm2m_jet_trend_30_u850,...
                    ipsl_cm5a_lr_jet_trend_30_u850,...
                    ipsl_cm5a_mr_jet_trend_30_u850,...
                    ipsl_cm5b_lr_jet_trend_30_u850,...
                    miroc_esm_jet_trend_30_u850,...
                    miroc_esm_chem_jet_trend_30_u850,...
                    miroc5_jet_trend_30_u850,...
                    mpi_esm_lr_jet_trend_30_u850,...
                    mpi_esm_mr_jet_trend_30_u850,...
                    mri_cgcm3_jet_trend_30_u850,...
                    nor_esm1m_m_jet_trend_30_u850,...
                    nor_esm1m_me_jet_trend_30_u850];
                
mean_trend_jet_loc = [can_esm2_mean_jet_loc,...
                      ccsm4_mean_jet_loc,...
                      cnrm_cm52_mean_jet_loc,...
                      gfdl_esm2m_mean_jet_loc,...
                      ipsl_cm5a_lr_mean_jet_loc,...
                      ipsl_cm5a_mr_mean_jet_loc,...
                      ipsl_cm5b_lr_mean_jet_loc,...
                      miroc_esm_mean_jet_loc,...
                      miroc_esm_chem_mean_jet_loc,...
                      miroc5_mean_jet_loc,...
                      mpi_esm_lr_mean_jet_loc,...
                      mpi_esm_mr_mean_jet_loc,...
                      mri_cgcm3_mean_jet_loc,...
                      nor_esm1m_m_mean_jet_loc,...
                      nor_esm1m_me_mean_jet_loc];

std_trend_jet_loc = [can_esm2_std_jet_loc,...
                      ccsm4_std_jet_loc,...
                      cnrm_cm52_std_jet_loc,...
                      gfdl_esm2m_std_jet_loc,...
                      ipsl_cm5a_lr_std_jet_loc,...
                      ipsl_cm5a_mr_std_jet_loc,...
                      ipsl_cm5b_lr_std_jet_loc,...
                      miroc_esm_std_jet_loc,...
                      miroc_esm_chem_std_jet_loc,...
                      miroc5_std_jet_loc,...
                      mpi_esm_lr_std_jet_loc,...
                      mpi_esm_mr_std_jet_loc,...
                      mri_cgcm3_std_jet_loc,...
                      nor_esm1m_m_std_jet_loc,...
                      nor_esm1m_me_std_jet_loc];
                  
historical_trend_loc = [can_esm2_jet_loc_trend_30_u850,...
                    ccsm4_jet_loc_trend_30_u850,...
                    cnrm_cm5_jet_loc_trend_30_u850,...
                    gfdl_esm2m_jet_loc_trend_30_u850,...
                    ipsl_cm5a_lr_jet_loc_trend_30_u850,...
                    ipsl_cm5a_mr_jet_loc_trend_30_u850,...
                    ipsl_cm5b_lr_jet_loc_trend_30_u850,...
                    miroc_esm_jet_loc_trend_30_u850,...
                    miroc_esm_chem_jet_loc_trend_30_u850,...
                    miroc5_jet_loc_trend_30_u850,...
                    mpi_esm_lr_jet_loc_trend_30_u850,...
                    mpi_esm_mr_jet_loc_trend_30_u850,...
                    mri_cgcm3_jet_loc_trend_30_u850,...
                    nor_esm1m_m_jet_loc_trend_30_u850,...
                    nor_esm1m_me_jet_loc_trend_30_u850];
                
x_axis = 1:length(mean_trend_jet_mag);
x_label = {'  ';'CanESM2'; 'CCSM4'; 'CNRM CM52'; 'GFDL ESM2M'; 'IPSL CM5A LR'; 'IPSL CM5A MR'; 'IPSL CM5B LR'; 'MIROC ESM'; 'MIROC ESM CHEM'; 'MIROC5'; 'MPI ESM LR'; 'MPI ESM MR'; 'MRI CGCM3'; 'NOR ESM1M M'; 'NOR ESM1M ME'; '  '}';

figure(1)
h1 = errorbar(x_axis,mean_trend_jet_mag,2.*std_trend_jet_mag);
hold on 
h2 = plot(x_axis, historical_trend, 'r*');
h3 = hline(jet_u850_trend_30);

set(h3, 'linestyle', '- -', 'linewidth', 2, 'color', [0, 0.8, 0])
set(h1,'marker','o', 'MarkerFaceColor', 'b')
set(h1,'linestyle','none')
set(gca, 'XTickLabel', x_label)
set(gca, 'XTick', 0:16)
rotateXLabels( gca, 45 )
ylim([-2.2 2.2])

print -depsc allmodels_jet_mag_whiskers


figure(2)
h1 = errorbar(x_axis,mean_trend_jet_loc,2.*std_trend_jet_loc);
hold on 
h2 = plot(x_axis, historical_trend_loc, 'r*');
h3 = hline(lat_u850_trend_30);

set(h3, 'linestyle', '- -', 'linewidth', 2, 'color', [0, 0.8, 0])
set(h1,'marker','o', 'MarkerFaceColor', 'b')
set(h1,'linestyle','none')
set(gca, 'XTickLabel', x_label)
set(gca, 'XTick', 0:16)
rotateXLabels( gca, 45 )
ylim([-6 6])

print -depsc allmodels_jet_loc_whiskers